version: '3.8'
name: dbt-bigquery

services:
  dbt:
    container_name: dbt
    build: .
    image: dbt:latest
    ports:
      - 8080:8080
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/service-account.json
    volumes:
      - .:/root/
    working_dir: /root
    tty: true